src/board/urls.py
# coding:utf-8
from rest_framework.routers import DefaultRouter

from . import views


board_router = DefaultRouter(trailing_slash=False)
board_router.register(r'sprints', views.SprintViewSet)
board_router.register(r'tasks', views.TaskViewSet)
board_router.register(r'users', views.UserViewSet)

src/scrum/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView
from rest_framework.authtoken.views import obtain_auth_token

from board.urls import board_router

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'scrum.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^api/token/', obtain_auth_token, name='api-token'),
    url(r'^api/', include(board_router.urls), name='api-root'),
    url(r'^$', TemplateView.as_view(template_name='board/index.html')),
)

src/board/models.py
# coding: utf-8
from django.conf import settings
from django.db import models


class TaskState(object):
    """ Enumerate of task states
    """
    TODO = 1
    PROGRESS = 2
    TESTING = 3
    DONE = 4

    values = {
        TODO: 'Не начато',
        PROGRESS: 'В работе',
        TESTING: 'В тестировании',
        DONE: 'Выполнено'
    }

    @classmethod
    def get_choices(cls):
        return tuple(cls.values.items())


class Sprint(models.Model):
    """ Sprint model
    """
    name = models.CharField(max_length=100, default='', blank=True)
    description = models.TextField(default='', blank=True)
    end = models.DateField(unique=True)

    def __str__(self):
        return self.name or 'Sprint ending %s' % self.end

    class Meta:
        db_table = 'sprint'


class Task(models.Model):
    """ Task model
    """
    name = models.CharField(max_length=100, default='', blank=True)
    description = models.TextField(default='', blank=True)
    sprint = models.ForeignKey('Sprint', blank=True, null=True)
    state = models.SmallIntegerField(choices=TaskState.get_choices(), default=TaskState.TODO)
    order = models.SmallIntegerField(default=0)
    assigned = models.ForeignKey(settings.AUTH_USER_MODEL, null=True, blank=True)
    started = models.DateField(null=True, blank=True)
    due = models.DateField(null=True, blank=True)
    completed = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.name

    @property
    def status_display(self):
        return TaskState.values[self.state]

    class Meta:
        db_table = 'task'

src/board/forms.py
# coding:utf-8
from django.contrib.auth import get_user_model
import django_filters

from .models import Task, Sprint


User = get_user_model()


class NullFilter(django_filters.BooleanFilter):
    """
    """
    def filter(self, qs, value):
        if value is not None:
            return qs.filter(**{self.name + '__isnull': value})
        return qs

class TaskFilter(django_filters.FilterSet):
    """
    """
    backlog = NullFilter(name='sprint')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.filters['assigned'].extra.update(to_field_name=User.USERNAME_FIELD)

    class Meta:
        model = Task
        fields = ('sprint', 'state', 'assigned', 'backlog')


class SprintFilter(django_filters.FilterSet):
    """
    """
    end_min = django_filters.DateFilter(name='end', lookup_type='gte')
    end_max = django_filters.DateFilter(name='end', lookup_type='lte')

    class Meta:
        model = Sprint
        fields = ('end_min', 'end_max')

src/board/views.py
import requests

from django.conf import settings
from django.contrib.auth import get_user_model
from rest_framework import authentication, permissions, filters
from rest_framework.viewsets import ModelViewSet, ReadOnlyModelViewSet

from .forms import TaskFilter, SprintFilter
from .models import Sprint, Task
from .serializers import SprintSerializer, TaskSerializer, UserSerializer


User = get_user_model()


class DefaultsMixin(object):
    """
    """
    authentication_classes = (
        authentication.BasicAuthentication,
        authentication.TokenAuthentication,
    )

    permission_classes = (
        permissions.IsAuthenticated,
    )

    paginate_by = 25
    paginate_by_param = 'page_size'
    max_paginate_by = 100
    filter_backends = (
        filters.DjangoFilterBackend,
        filters.SearchFilter,
        filters.OrderingFilter,
    )


class UpdateHookMixin(object):
    """ Миксин отправки сообщений об обновлениях через вебсокет
    """
    def _build_hook_url(self, obj):
        if isinstance(obj, User):
            model = 'user'
        else:
            model = obj.__class__.__name__.lower()
        return '{}://{}/{}/{}'.format(
            'https' if settings.WATERCOOLER_SECURE else 'http',
            settings.WATERCOOLER_SERVER,
            model,
            obj.pk
        )

    def _send_hook_request(self, obj, method):
        url = self._build_hook_url(obj)
        try:
            response = requests.request(method, url, timeout=0.5)
            response.raise_for_status()
        except requests.ConnectionError:
            pass
        except requests.Timeout:
            pass
        except requests.RequestException:
            pass

    def post_save(self, obj, created=False):
        method = 'POST' if created else 'PUT'
        self._send_hook_request(obj, method)

    def pre_delete(self, obj):
        self._send_hook_request(obj, 'DELETE')


class SprintViewSet(DefaultsMixin, UpdateHookMixin, ModelViewSet):
    """
    """
    queryset = Sprint.objects.order_by('end')
    serializer_class = SprintSerializer
    filter_class = SprintFilter
    search_fields = ('name',)
    ordering_fields = ('end', 'name')


class TaskViewSet(DefaultsMixin, UpdateHookMixin, ModelViewSet):
    """
    """
    queryset = Task.objects.all()
    serializer_class = TaskSerializer
    filter_class = TaskFilter
    search_fields = ('name', 'description',)
    ordering_fields = ('name', 'order', 'started', 'due', 'completed')


class UserViewSet(DefaultsMixin, UpdateHookMixin, ReadOnlyModelViewSet):
    """
    """
    lookup_field = User.USERNAME_FIELD
    lookup_url_kwarg = User.USERNAME_FIELD
    queryset = User.objects.order_by(User.USERNAME_FIELD)
    serializer_class = UserSerializer
    search_fields = (User.USERNAME_FIELD,)

src/board/templates/board/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html class="no-js">
<head lang="en">
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-COMPATIBLE" content="IE=edge">
    <title>Scrum board</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'board/vendor/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'board/css/board.css' %}">
    <script type="text/html" id="home-template">
        <h2>Спринты</h2>
        <button class="add" type="submit">Добавить спринт</button>
        <% if (sprints !== null) { %>
            <div class="sprints">
                <% _.each(sprints.models, function (sprint) { %>
                    <a href="#sprint/<%- sprint.get('id') %>" class="sprint">
                        <%- sprint.get('name') %><br>
                        <span>завершается <%- sprint.get('end') %></span>
                    </a>
                <% }); %>
            </div>
        <% } else { %>
            <h3 class="loading">Загрузка ...</h3>
        <% } %>
    </script>
    <script type="text/html" id="login-template">
        <form action="" method="post">
            <label for="id_username">Логин</label>
            <input id="id_username" type="text" name="username" maxlength="30" required>
            <label for="id_password">Пароль</label>
            <input id="id_password" type="password" name="password" required>
            <button type="submit">Войти</button>
        </form>
    </script>
    <script type="text/html" id="header-template">
        <span class="title">Скрам-доска (пример)</span>
        <% if (authenticated) { %>
            <nav>
                <a href="/" class="button">Спринты</a>
                <a href="#" class="logout button">Выйти</a>
            </nav>
        <% } %>
    </script>
    <script type="text/html" id="new-sprint-template">
        <form action="" method="post">
            <label for="id_name">Наименование</label>
            <input id="id_name" type="text" name="name" maxlength="100" required />
            <label for="id_end">Дата окончания</label>
            <input id="id_end" type="date" name="end" />
            <label for="'id_description">Примечание</label>
            <textarea id="'id_description" name="description" cols="50"></textarea>
            <button class="cancel">Отмена</button>
            <button type="submit">Создать</button>
        </form>
    </script>
    <script type="text/html" id="sprint-template">
        <% if (sprint !== null) { %>

            <% if (!sprint.invalid) { %>
                <h2><%- sprint.get('name') %></h2>
                <span class="due-date">Дата завершения: <%- sprint.get('end') %></span>
                <p class="description"><%- sprint.get('description') %></p>
                <div class="tasks"></div>
            <% } else { %>
                <h1>Спринт <%- sprint.get('id') %> не найден </h1>
            <% } %>
        <% } else { %>
            <h1 class="loading">Загрузка ...</h1>
        <% } %>
    </script>
    <script type="text/html" id="status-template">
        <h4><%- title %></h4>
        <div class="list"></div>
        <% if (sprint === null) { %>
            <button class="add" type="submit">Добавить задачу</button>
        <% } %>
    </script>
    <script type="text/html" id="new-task-template">
        <form class="add-task" action="" method="post">
            <label for="id_name">Наименование</label>
            <input id="id_name" type="text" name="name" maxlength="100" required />
            <label for="id_description">Содержание</label>
            <textarea id="id_description" name="description"></textarea>
            <button class="create" type="submit">Создать</button>
            <button class="cancel" type="submit">Отмена</button>
        </form>
    </script>
    <script type="text/html" id="task-item-template">
        <%- task.get('name') %>
    </script>
    <script type="text/html" id="task-detail-template">
        <div data-field="name" class="name" contenteditable="true">
            <%- task.get('name') %>
        </div>
        <div data-field="description" class="description" contenteditable="true">
            <%- task.get('description') %>
        </div>
        <div class="with-label">
            <div class="label">Дата окончания: </div>
            <div data-field="due" class="due-date" contenteditable="true">
                <%- task.get('due') || empty %>
            </div>
        </div>
        <div class="with-label">
            <div class="label">Назначен: </div>
            <div data-field="assigned" class="assigned" contenteditable="true">
                <%- task.get('assigned') || empty %>
            </div>
        </div>
        <form>
            <button class="cancel" type="submit">Закрыть</button>
            <button class="save hide" type="submit">Сохранить</button>
        </form>
    </script>
</head>
<body>
    <div id="content"></div>
    <script src="{% static 'board/vendor/jquery.js' %}"></script>
    <script src="{% static 'board/vendor/underscore.js' %}"></script>
    <script src="{% static 'board/vendor/backbone.js' %}"></script>
    <script id="config" type="text/json">
        {
            "models": {},
            "collections": {},
            "session": null,
            "views": {},
            "router": null,
            "apiRoot": "{% url 'api-root' %}",
            "apiLogin": "{% url 'api-token' %}"
        }
    </script>
    <script src="{% static 'board/js/app.js' %}"></script>
    <script src="{% static 'board/js/socket.js' %}"></script>
    <script src="{% static 'board/js/models.js' %}"></script>
    <script src="{% static 'board/js/views.js' %}"></script>
    <script src="{% static 'board/js/router.js' %}"></script>
</body>
</html>